### PR TITLE
Restructure scripts output

### PR DESCRIPTION
**Pull request by kurttaylor**
Changes to the "analysis" folder where scripts are stored and "output" folder. The aim was to make these tidier and easier to navigate.

### CODE REVIEW

**Comment by kurttaylor** [comment]
This is now running successfully locally for me (but not in actions).

**Comment by venexia** [comment]
I am getting the following error:

`Fatal error: cannot open file 'analysis/descriptives/venn_diagram.R': No such file or directory`

It looks like the venn_diagram.R script was deleted from `supplementary-tables-figures` but not added to `descriptives`. Please can you put this file back into the repo?

**Comment by kurttaylor** [comment]
@venexia I have just updated. For some reason the gitignore was changed - sorry about that. I have just reverted the gitignore to the version on the main branch and the Venn script should now be present.

**Comment by venexia** [comment]
In terms of adding directories, this PR is working and can be merged to main. The PR is failing the checks due to a memory error and I am having the same issue locally but this usually resolves in the real data and I don't think relates to the contents of this PR.

**Comment by venexia** [comment]
I have a personal preference for simpler directory names - see suggestions below - but this is personal so feel free to ignore:

- analysis/cox-analysis > analysis/model
- analysis/data-preprocess-cleaning > analysis/preprocess
- analysis/supplementary-tables-figures > analysis/supplement
- output/for-review > output/review
- output/for-review/cox-analysis > output/for-review/model
- output/for-review/data-for-figures > output/for-review/figure-data

**Comment by venexia** [comment]
I also wonder whether the .rds files in 'output/not-for-review' should be moved up to the output directory as these are the data files we are working with. All other files in this folder are data check type things that we view on the server so there is a bit of distinction there. Again, this is personal preference so feel free to ignore.

**Review by venexia — APPROVED** [review]

**Comment by kurttaylor** [comment]
Thanks @venexia - I agree with your additional suggestions and these are now incorporated. Actions running successfully (on one outcome).

**Pull request merged**
